* [[https://quernd.github.io/tutorials/tea-chess][A chess-themed tutorial on writing an SPA in Bucklescript-TEA]]

I recently started frontend web development in [[https://ocaml.org/][OCaml]] by using
[[https://bucklescript.github.io/][Bucklescript]] to compile my code into Javascript. Naturally, a
functional language like OCaml goes well together with the famous [[https://guide.elm-lang.org/architecture/][Elm
architecture]], so I chose to explore the recent [[https://github.com/OvermindDL1/bucklescript-tea][Bucklescript-TEA]]
library. (TEA stands for "The Elm Architecture", obviously.)

OCaml and Bucklescript have recently gained a lot of attention, not
least because of Facebook's [[https://reasonml.github.io/][Reason]] -- an alternative, more
Javascript-like syntax for OCaml. I prefer the traditional OCaml
syntax, but you can use either syntax together with Bucklescript.

In this tutorial, I will walk you through an entire example of a
single-page application. It will certainly help if you have a little
experience with chess, web development and in particular functional
programming in general or OCaml in particular, but it is no
prerequisite, you can pick up everything you need on the way.
